# ===============================
# HTTP
# ===============================
quarkus.http.port=8080
quarkus.http.root-path=/project

# ===============================
# DATASOURCE - H2 (IN MEMORY)
# ===============================
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:projectdb
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

# ===============================
# HIBERNATE ORM
# ===============================
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
